site_name: XP Wiki
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'
nav:
    - 导航: index.md
    - 规则:
      - V4.x规则:
        - 序章：简介: rules/V4.x rules/prologue.md
        - 第一章：属性: rules/V4.x rules/1·attribute.md
        - 第二章：种族: rules/V4.x rules/2·race.md
        - 第三章：技能: rules/V4.x rules/3·skills.md
        - 第四章：职业: rules/V4.x rules/4·occupation.md
        - 第五章：社群: rules/V4.x rules/5·social.md
        - 第六章：战斗: rules/V4.x rules/6·battle.md
        - 第七章：子弹时间与破绽: rules/V4.x rules/Extra/BulletTime.md
        - 第八章：魔法: rules/V4.x rules/8·magic.md
        - 第九章：角色专属技能: rules/V4.x rules/9·individualSkill.md
        - 第十章：天命: rules/V4.x rules/10·fate.md
        - 第十一章：资源: rules/V4.x rules/11·resources.md
        - 车卡指南: rules/V4.x rules/tutorial.md
        - 扩展规则:
          - 骑乘战斗(4.x): rules/V4.x rules/Extra/Riding.md
          - 长休规则: rules/V3.8rules/rest.md
          - 随从: rules/V4.x rules/Extra/Entourage.md
          - 重量规则: rules/V4.x rules/Extra/Weight.md
          - 潜行与反隐规则: rules/V4.x rules/Extra/Stealth.md
        - 旧设备份:
          - 职业设定: rules/V4.x rules/Back/old_occupation.md
          - 社群设定: rules/V4.x rules/Back/old_social.md
      - V3.8规则:
        - 规则书: rules/V3.8rules/mainRules.md
        - 扩展规则:
          - 子弹时间: rules/V3.8rules/bulletTime.md
          - 骑乘战斗: rules/V3.8rules/ridingBattle.md
          - 料理规则: rules/V3.8rules/cook.md
          - 竞速规则: rules/V3.8rules/contest.md
          - 轻量级副本探索规则: rules/V3.8rules/mapFarm.md
    - 游戏数据:
      - 技能升级:
        - 泛用技能熟练度升级: rules/data/update/skills.md
        - 武器熟练度升级: rules/data/update/weapons.md
        - 通用武器技能: rules/data/update/universal.md
        - 战术技能: rules/data/update/tactics.md
        - 驯兽熟练度升级: rules/data/update/mount.md
        - 通用坐骑技能: rules/data/update/mountUniversal.md
      - 魔法书:
        - 塑型土: rules/data/magic/plastic_Soil.md
        - 元素类魔法:
          - 火系魔法: rules/data/magic/elemental/fire.md
          - 水系魔法: rules/data/magic/elemental/water.md
          - 雷系魔法: rules/data/magic/elemental/thunder.md
          - 土系魔法: rules/data/magic/elemental/earth.md
          - 气系魔法: rules/data/magic/elemental/air.md
        - 自然类魔法:
          - 丛林系魔法: rules/data/magic/natural/forest.md
          - 山岳系魔法: rules/data/magic/natural/mountain.md
          - 川流系魔法: rules/data/magic/natural/river.md
          - 大地系魔法: rules/data/magic/natural/ground.md
          - 岩窟系魔法: rules/data/magic/natural/dungeon.md
          - 荒漠系魔法: rules/data/magic/natural/sand.md
        - 炼金类魔法:
          - 冶金系魔法: rules/data/magic/alchemy/metallurgy.md
          - 医药系魔法: rules/data/magic/alchemy/medical.md
          - 符文系魔法: rules/data/magic/alchemy/rune.md
        - 信仰类魔法:
          - 西方大陆:
            - 圣光魔法: rules/data/magic/faith/west/holy.md
          - 天狗国:
            - 八咫鸟大神: rules/data/magic/faith/Tengu/yatagarasuKami.md
            - 斗争大神: rules/data/magic/faith/Tengu/tatakaiKami.md
            - 锻造大神: rules/data/magic/faith/Tengu/tanzouKami.md
            - 稻荷大神: rules/data/magic/faith/Tengu/inariKami.md
            - 荒胫大神: rules/data/magic/faith/Tengu/arasuneKami.md
            - 开拓大神: rules/data/magic/faith/Tengu/kaitakuKami.md
            - 梅山: rules/data/magic/faith/Tengu/umeyama.md
          - 大鸿:
            - 大鸿军理: rules/data/magic/faith/GreatHong/JunLi.md
        - 心灵类魔法: rules/data/magic/mind.md
        - 鲜血系魔法: rules/data/magic/blood.md
        - 暗影系魔法: rules/data/magic/shadow.md
        - 3.8规则旧设:
          - 元素类魔法: rules/data/magic/elemental.md
          - 自然类魔法: rules/data/magic/natural.md
          - 炼金类魔法: rules/data/magic/alchemy.md
          - 召唤类魔法: rules/data/magic/summon.md
      - 社群与职业:
        - 集群规模表: rules/data/social/scaleList.md
        - 汇率: rules/data/social/exchangeRate.md
        - 基础职业:
          - ★武者: rules/data/social/basicJob/Warrior.md
          - ★哨兵: rules/data/social/basicJob/Sentinel.md
          - ★卫士: rules/data/social/basicJob/Guard.md
          - ★旗手: rules/data/social/basicJob/Standard-bearer.md
          - ☆专家: rules/data/social/basicJob/Specialist.md
        - 西方大陆:
          - 封土（世袭领地）:
            - 社群简介: rules/data/social/universal/feoff/feoff.md
            - 进阶职业:
              - ★步兵: rules/data/social/universal/feoff/footman.md
              - ★扈从: rules/data/social/universal/feoff/squire.md
              - ★★骑士: rules/data/social/universal/feoff/knight.md
          - 圣堂:
            - 社群简介: rules/data/social/universal/sanctuary/sanctuary.md
            - 进阶职业:
              - ★修士/修女: rules/data/social/universal/sanctuary/friar_nun.md
              - ★★诵经师: rules/data/social/universal/sanctuary/chanter.md
              - ★★★圣裁官: rules/data/social/universal/sanctuary/inquisitor.md
          - 精灵家族领:
            - 社群简介: rules/data/social/universal/elfFamily/elfFamily.md
            - 进阶职业:
              - ★守望者: rules/data/social/universal/elfFamily/watcher.md
              - ★★游侠: rules/data/social/universal/elfFamily/ranger.md
              - ★★猎师: rules/data/social/universal/elfFamily/huntMaster.md
          - Zwei佣兵团:
            - 社群简介: rules/data/social/universal/zwei/zwei.md
            - 进阶职业:
              - ★Zwei佣兵: rules/data/social/universal/zwei/zwei-mercenary.md
              - ★★Zwei重剑士: rules/data/social/universal/zwei/zwei-heavy-swordsman.md
              - ★★Zwei暗袭者: rules/data/social/universal/zwei/zwei-assassin.md
              - ★★Zwei近弓手: rules/data/social/universal/zwei/zwei-archer.md
              - ★★Zwei佣兵队长: rules/data/social/universal/zwei/zwei-commander.md
          - 魔法学院:
            - 社群简介: rules/data/social/universal/magicSchool/magicSchool.md
            - 进阶职业:
              - ★魔法学徒: rules/data/social/universal/magicSchool/apprentice.md
              - ★★魔法进修生: rules/data/social/universal/magicSchool/postgraduate.md
              - ★★★魔法教授: rules/data/social/universal/magicSchool/professor.md
        - 大鸿:
          - 郡县:
            - 社群简介: rules/data/social/GreatHong/Jun&Xian/Jun&Xian.md
            - 乡勇: rules/data/social/GreatHong/Jun&Xian/militiamen.md
            - 进阶职业:
              - ★小吏: rules/data/social/GreatHong/Jun&Xian/beadle.md
              - ★★士大夫: rules/data/social/GreatHong/Jun&Xian/bureaucrat.md
          - 相剑道门:
            - 社群简介: rules/data/social/GreatHong/XiangJian_Sect/XiangJian_Sect.md
            - 进阶职业:
              - ★相剑学徒: rules/data/social/GreatHong/XiangJian_Sect/XiangJian_Apprentice.md
              - ★★相剑师: rules/data/social/GreatHong/XiangJian_Sect/XiangJian_Artisan.md
              - ★★★相剑大师: rules/data/social/GreatHong/XiangJian_Sect/XiangJian_Master.md
          - 拜龙密教:
            - 社群简介: rules/data/social/GreatHong/abyssesotericism/abyssesotericism.md
            - 渗透系统: rules/data/social/GreatHong/abyssesotericism/infiltration.md
            - 进阶职业:
              - ★虔信徒: rules/data/social/GreatHong/abyssesotericism/devotedcultist.md
              - ★★狞教士: rules/data/social/GreatHong/abyssesotericism/grimnarchclergy.md
              - ★★播信师: rules/data/social/GreatHong/abyssesotericism/faithspreader.md
              - ★★★蚀锋卫: rules/data/social/GreatHong/abyssesotericism/bladecorroder.md
              - ★★★处刑人: rules/data/social/GreatHong/abyssesotericism/executioner.md
              - ★★★守尸客: rules/data/social/GreatHong/abyssesotericism/bodykeeper.md
              - ★★★邪术师: rules/data/social/GreatHong/abyssesotericism/cultwizard.md
              - ★★★唤龙使: rules/data/social/GreatHong/abyssesotericism/dragonsummoner.md
          - 绝艺画院:
            - 社群简介: rules/data/social/GreatHong/artistgroup/artistgroup.md
            - 墨法书:
              - 彩艺教典: rules/data/social/GreatHong/artistgroup/artist_magicbook/Colorful_Codex.md
              - 塑灵伪典: rules/data/social/GreatHong/artistgroup/artist_magicbook/Shaper_Pseudepigrapha.md
              - 墨法原典: rules/data/social/GreatHong/artistgroup/artist_magicbook/Traditional_Canonical.md
            - 进阶职业:
              - ★研墨门徒: rules/data/social/GreatHong/artistgroup/artist_sect/Artist_Apprentice.md
              - ★★异彩涂客: rules/data/social/GreatHong/artistgroup/artist_sect/Colorful_Artist.md
              - ★★黯绘塑师: rules/data/social/GreatHong/artistgroup/artist_sect/Shaper_Artist.md
              - ★★水墨画工: rules/data/social/GreatHong/artistgroup/artist_sect/Traditional_Artist.md
              - ★★★万艺巨匠: rules/data/social/GreatHong/artistgroup/artist_sect/Versatile_Colossus.md
          - 武术段位等级: rules/data/social/GreatHong/MartialLevel.md
          - 武术:
            - ☆☆开门拳: rules/data/social/GreatHong/Martial_Arts/Gatebuster.md
          - 玉峰剑派（待重置）: rules/data/social/GreatHong/YuFeng.md
        - 天狗国:
          - 士幕府:
            - 社群简介: rules/data/social/Tengu/bakufu/bakufu.md
            - 进阶职业:
              - ★★武士: rules/data/social/Tengu/bakufu/samurai.md
              - ★★旗本大将: rules/data/social/Tengu/bakufu/hatamoto_taishou.md
              - ★★旗本马回众: rules/data/social/Tengu/bakufu/hatamoto_umamawarishu.md
              - ☆☆奉行: rules/data/social/Tengu/bakufu/bugyou.md
              - ★★★大名: rules/data/social/Tengu/bakufu/daimyou.md
          - 神社:
            - 社群简介: rules/data/social/Tengu/jinja/jinja.md
            - 进阶职业:
              - ★祝/巫女: rules/data/social/Tengu/jinja/shuku_miko.md
              - ★★御祝/御巫女: rules/data/social/Tengu/jinja/oshuku_omiko.md
          - 忍者屋敷:
            - 社群简介: rules/data/social/Tengu/shinobi_yashiki/shinobi_yashiki.md
            - 进阶职业:
              - ★下忍: rules/data/social/Tengu/shinobi_yashiki/genin.md
              - ★★中忍: rules/data/social/Tengu/shinobi_yashiki/chunin.md
              - ★★★上忍: rules/data/social/Tengu/shinobi_yashiki/jounin.md
          - 御庭番:
            - 社群简介: rules/data/social/Tengu/oniwagen/oniwagen.md
            - 进阶职业:
              - ★★目付: rules/data/social/Tengu/oniwagen/metsuke.md
              - ★★★御空行者: rules/data/social/Tengu/oniwagen/osora_gyouja.md
              - ★★★御地行者: rules/data/social/Tengu/oniwagen/otsuchi_gyouja.md
              - ★★★御海行者: rules/data/social/Tengu/oniwagen/oumi_gyouja.md
          - 源流报社:
            - 社群简介: rules/data/social/Tengu/genryu_shinbunsha/genryu_shinbunsha.md
            - 进阶职业:
              - ★编辑: rules/data/social/Tengu/genryu_shinbunsha/editor.md
              - ★执笔: rules/data/social/Tengu/genryu_shinbunsha/writer.md
              - ★摄影: rules/data/social/Tengu/genryu_shinbunsha/photographer.md
              - ★信使: rules/data/social/Tengu/genryu_shinbunsha/messenger.md
          - 鳞海戍卫军:
            - 社群简介: rules/data/social/Tengu/seaDragonGuard/seaDragonGuard.md
            - 进阶职业:
              - ★列兵: rules/data/social/Tengu/seaDragonGuard/enlistedpersonnel.md
              - ★士官: rules/data/social/Tengu/seaDragonGuard/noncommissionedofficer.md
              - ★★尉官: rules/data/social/Tengu/seaDragonGuard/lieutenant.md
              - ★★★校官（战斗岗）: rules/data/social/Tengu/seaDragonGuard/battlecadet.md
              - ★★★校官（研究岗）: rules/data/social/Tengu/seaDragonGuard/r&dcadet.md
          - 段位与流派: rules/data/social/Tengu/dan.md
          - 剑术流派:
            - 进阶职业:
              - ☆☆集心流: rules/data/social/Tengu/kenjutsu/shushin_ryu.md
              - ☆☆缭乱流: rules/data/social/Tengu/kenjutsu/ryouran_ryu.md
              - ☆☆野兽流: rules/data/social/Tengu/kenjutsu/yaju_ryu.md
          - 桐坂众（桐坂流）:
            - 社群简介: rules/data/social/Tengu/kirisaki_ryu/kirisaki_ryu.md
            - 进阶职业:
              - ★★散兵: rules/data/social/Tengu/kirisaki_ryu/skirmisher.md
              - ★★★尖兵: rules/data/social/Tengu/kirisaki_ryu/vanguard.md
              - ★★狙击手: rules/data/social/Tengu/kirisaki_ryu/sniper.md
              - ★★★枪眼: rules/data/social/Tengu/kirisaki_ryu/gunEye.md
              - ★★战勤: rules/data/social/Tengu/kirisaki_ryu/service.md
              - ★★★司务: rules/data/social/Tengu/kirisaki_ryu/secretary.md
          - 北乡府:
            - 社群简介: rules/data/social/Tengu/nao_the_prince/nao_the_profile.md
            - 进阶职业:
              - ★镙纹御前（近海巫女）: rules/data/social/Tengu/nao_the_prince/ramongozen.md
              - ★海族指挥使: rules/data/social/Tengu/nao_the_prince/umiumeshikikan.md
              - ★★钿珠女命: rules/data/social/Tengu/nao_the_prince/denjumenomikoto.md
              - ★★海族智者: rules/data/social/Tengu/nao_the_prince/umiumenochisha.md
        - 魔族:
          - 魔族基础职业:
            - ☆魔族公民: rules/data/social/monman/basicJob/citizen.md
            - ☆穿界者: rules/data/social/monman/basicJob/interWorlder.md
          - 巨兽猎手:
            - 社群简介: rules/data/social/monman/hugeHunter/hugeHunter.md
            - 进阶职业:
              - ★巨兽猎兵: rules/data/social/monman/hugeHunter/jager.md
              - ★★追迹猎手: rules/data/social/monman/hugeHunter/chaser.md
              - ★★驯兽师: rules/data/social/monman/hugeHunter/tamer.md
              - ★★★围猎大师: rules/data/social/monman/hugeHunter/siegeMaster.md
          - 明光学联:
            - 社群简介: rules/data/social/monman/lightUnion/lightUnion.md
            - 光耀系魔法书: rules/data/social/monman/lightUnion/lightMagic.md
            - 进阶职业:
              - ★微光学徒: rules/data/social/monman/lightUnion/lightApprentice.md
              - ★烁光工匠: rules/data/social/monman/lightUnion/lightArtisan.md
              - ★★明光学士: rules/data/social/monman/lightUnion/lightBachelor.md
              - ★★辉光巧匠: rules/data/social/monman/lightUnion/lightCraftsman.md
              - ★★吸光龙影: rules/data/social/monman/lightUnion/dragonShadow.md
              - ★★披光猎手: rules/data/social/monman/lightUnion/lighthuntsman.md
              - ★★★耀光学者: rules/data/social/monman/lightUnion/lightMaster.md
              - ★★★流光乱匠: rules/data/social/monman/lightUnion/lightArtist.md
              - ★★★暮光龙侯: rules/data/social/monman/lightUnion/dragoner.md
              - ★★★影光猎户: rules/data/social/monman/lightUnion/lightmarksman.md
              - ☆☆烈光骁骑: rules/data/social/monman/lightUnion/sunKnight.md
              - ☆☆柔光从骑: rules/data/social/monman/lightUnion/moonKnight.md
      - 单位:
        - 召唤单位:
          - 魔像: rules/data/unit/summon/golem.md
          - 石兽: rules/data/unit/summon/stoneBeast.md
          - 迷你战车: rules/data/unit/summon/miniChariot.md
          - 神龛: rules/data/unit/summon/shrine.md
          - 棋塔: rules/data/unit/summon/chessTower.md
          - 巨像: rules/data/unit/summon/titan.md
          - 影狼: rules/data/unit/summon/shadowWolf.md
          - 鸡蛇兽: rules/data/unit/summon/cockatrice.md
          - 战猪: rules/data/unit/summon/battleBoar.md
          - 巨蜥: rules/data/unit/summon/goanna.md
          - 战熊: rules/data/unit/summon/warBear.md
          - 低阶骷髅: rules/data/unit/summon/lowSkeleton.md
          - 低阶僵尸: rules/data/unit/summon/lowZombie.md
        - 魔族:
          - 巨兽猎手（废案备份）:
            - 巨兽猎兵: rules/data/unit/monman/hugeHunter/huntman.md
            - 追迹猎手: rules/data/unit/monman/hugeHunter/pathHunter.md
            - 驯兽师: rules/data/unit/monman/hugeHunter/tamer.md
        - 天狗国:
          - 桐坂众（废案备份）:
            - 桐坂众散兵: rules/data/unit/tengu/kirisaki/skirmisher.md
            - 桐坂众狙击手: rules/data/unit/tengu/kirisaki/sniper.md
            - 桐坂众战勤: rules/data/unit/tengu/kirisaki/service.md
      - 装备:
        - 武器及其平均性能表: rules/data/equipment/weapons.md
        - 防具及其平均性能表: rules/data/equipment/armor.md
        - 道具列表: rules/data/equipment/item.md
        - 坐骑及其平均性能表: rules/data/equipment/mount.md
        - 坐骑防具及其平均性能表: rules/data/equipment/mountArmor.md
    - 世界观设定:
      - 世界群理论:
        - 世界群的形成: settings/forming.md
        - 灵魂循环机制与智慧生命的形成: settings/soul.md
        - 上层世界: settings/upper.md
        - 中层世界: settings/middle.md
        - 下层世界: settings/downer.md
      - 文明简介:
        - 鸿国:
          - 大鸿国家概况: settings/civilization/GreatHong/GreatHong.md
        - 西方大陆:
          - 人类联合王国国家概况: settings/civilization/Westland/human/summary.md
          - 木精灵社群国家概况: settings/civilization/Westland/woodElf/summary.md
          - 沙漠帝国国家概况: settings/civilization/Westland/sandEmpire/summary.md
          - 蚁族夜镰商会概况: settings/civilization/Westland/NightSickle/NightSickle.md
          - 黎云组织概况: settings/civilization/Westland/DawnCloud/DawnCloud.md
          - 种族:
            - 人类: settings/civilization/Westland/human/human.md
            - 精灵: settings/civilization/Westland/woodElf/elf.md
            - 北方沙族: settings/civilization/Westland/sandEmpire/sandMan.md
            - 蚁族: settings/civilization/Westland/NightSickle/antMan.md
        - 天狗国:
          - 天狗国国家概况: settings/civilization/Tengu/summary.md
          - 天狗国的姓名构成: settings/civilization/Tengu/name.md
          - 种族:
            - 鸦天狗: settings/civilization/Tengu/karasu.md
            - 狐天狗: settings/civilization/Tengu/kitsune.md
            - 鲸天狗: settings/civilization/Tengu/gujira.md
        - 魔族:
          - 魔族国家概况: settings/civilization/Monman/summary.md
          - 魂源与魂源网络: settings/civilization/Monman/soulmine.md
          - 种族:
            - 鬼族: settings/civilization/Monman/demon.md
            - 亡灵生物: settings/civilization/Monman/ghost.md
            - 美杜莎: settings/civilization/Monman/medusa.md
      - 大事年表:
        - 魔族大事年表: settings/chronology/Monman.md
        - 大鸿大事年表: settings/chronology/GreatHong.md
        - 天狗国·海族秘史: settings/chronology/umi_ume.md
      - 重大战役简介:
        - 贝塞克顿战役: settings/campaign/bicycleton.md
        - 第二次人界内战（未完）: settings/campaign/secondHumanVsElf.md
      - 魔法理论:
        - 魔法百科全书（未完）: settings/magic/magicBook.md
    - 创作缓冲区:
      - 说明: temp/index.md
      - 如何开始创作: temp/tutorial.md
      - 秋田创作区:
        - 说明: temp/akita/akita_profile.md
        - 小说:
          - 佘镇故事补: temp/akita/shezhen_story/shezhen-1.md
        - 图画:
          - 露娜: temp/akita/lunaluna.png
        - 梅尔里夫国立地理所:
          - 社群简介: temp/akita/mererif_geo_center/geo_center_profile.md
          - ★初级测绘师: temp/akita/mererif_geo_center/primeSurveyor.md
      - 苍术创作区:
        - 魔百（非官方）: temp/cangzhu/magic.md
      - 地猫创作区:
        - 说明: temp/DMAL/DMAL_profile.md
        - 乐府社群:
          - 社群简介: temp/DMAL/Musician_Sect/Musician_Sect.md
          - ★教坊学徒: temp/DMAL/Musician_Sect/Musician_Apprentice.md
        - 武术流派:
          - ★开门拳: temp/DMAL/Martial arts/Gatebuster.md
      - 像素头创作区:
        - 说明: temp/pixelhead/introduce.md
        - 修改意见: temp/pixelhead/debug.md
        - F&Q:
          - 高维生物: temp/pixelhead/FA♂Q/high.md
          - 高维空间、魔界、幽灵性质: temp/pixelhead/FA♂Q/highmonghost.md
          - 魔法学院高层相关: temp/pixelhead/FA♂Q/magicschoolleader.md
          - 魔法学院招生政策及立场相关: temp/pixelhead/FA♂Q/magicschoolnewpeople.md
          - 关于穿界门的一些问题: temp/pixelhead/FA♂Q/portal.md
        - 画师社群社群:
          - 社群简介: temp/pixelhead/artistgroup/artistgroup.md
      - 黑羽魇鸽创作区:
        - 说明: temp/DeatLvens/introduce.md
        - 修改意见: temp/DeatLvens/debug.md
        - 廻天流: temp/DeatLvens/kaiten_ryu.md
        - 死翼鸟社群: 
          - 社群简介: temp/DeatLvens/Deathbird/Deathbird(union).md
          - ★影羽: temp/DeatLvens/Deathbird/ShadowFeather.md
          - ★血爪: temp/DeatLvens/Deathbird/BloodyClaw.md
          - ★★魇羽: temp/DeatLvens/Deathbird/FrighteningFeather.md
          - ★★血喙: temp/DeatLvens/Deathbird/BloodyBeak.md
          - ☆☆瘴骨: temp/DeatLvens/Deathbird/MiasmBone.md
          - ★★★死翼鸟: temp/DeatLvens/Deathbird/DeathBird.md
          - 暗影系魔法书: temp/DeatLvens/ShadowMagic.md


theme:
  name: material
  features:
    - navigation.tabs
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.caret
